import re
with open("panel-candidatos/assets/index-BF1UmWzM.js", "r") as f:
    content = f.read()

old_timeout = r'setTimeout\(\(\)=>{ document\.querySelectorAll\("\.cand__status--waiting, \.cand__status--actionable"\)\.forEach\(el => \{ if\(el\.innerText\.includes\("Esperando"\) \|\| el\.innerText\.includes\("acción"\)\) \{ el\.className = "cand__status cand__status--success"; el\.innerHTML = "<span class=\\"cand__status-dot\\" aria-hidden=\\"true\\"></span>Completado"; \} \}\); document\.querySelectorAll\("div\.rounded-xl\.border\.overflow-hidden"\)\.forEach\(card => \{ if\(card\.innerText\.includes\("Esperando acción manual"\)\) \{ const badge = card\.querySelector\("span\.bg-amber-50"\); if\(badge\) \{ badge\.className = badge\.className\.replace\("text-amber-700", "text-emerald-700"\)\.replace\("border-amber-400", "border-emerald-300"\)\.replace\("bg-amber-50", "bg-emerald-50"\); badge\.innerText = "Completado"; \} const amberText = card\.querySelector\("\.text-amber-600"\); if\(amberText\) \{ amberText\.style\.display = "none"; \} card\.querySelectorAll\("button"\)\.forEach\(b => \{ if\(b\.innerText\.includes\("Activar"\)\) \{ b\.style\.display = "none"; \} \}\); const numBadge = card\.querySelector\("\.w-8\.h-8, \.w-9\.h-9"\); if\(numBadge\) \{ numBadge\.className = numBadge\.className\.replace\("bg-gray-100", "bg-emerald-50"\)\.replace\("border-gray-200", "border-emerald-200"\)\.replace\("text-gray-500", "text-emerald-600"\); numBadge\.innerHTML = "<svg xmlns=\\"http://www.w3.org/2000/svg\\" width=\\"24\\" height=\\"24\\" viewBox=\\"0 0 24 24\\" fill=\\"none\\" stroke=\\"currentColor\\" stroke-width=\\"2\\" stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\" class=\\"lucide lucide-check w-4 h-4 text-emerald-600\\"><path d=\\"M20 6 9 17l-5-5\\"></path></svg>"; \} \} \}\); \}, 100\);'

new_timeout = r'''let count=0; let intv = setInterval(()=>{ count++; if(count>20) clearInterval(intv); document.querySelectorAll(".cand__status--waiting, .cand__status--actionable").forEach(el => { if(el.textContent.includes("Esperando") || el.textContent.includes("acción")) { el.className = "cand__status cand__status--success"; el.innerHTML = "<span class=\"cand__status-dot\" aria-hidden=\"true\"></span>Completado"; } }); document.querySelectorAll("div.rounded-xl.border.overflow-hidden").forEach(card => { if(card.textContent.includes("Esperando acción manual")) { const badge = card.querySelector("span.bg-amber-50"); if(badge) { badge.className = badge.className.replace("text-amber-700", "text-emerald-700").replace("border-amber-400", "border-emerald-300").replace("bg-amber-50", "bg-emerald-50"); badge.textContent = "Completado"; } const amberText = card.querySelector(".text-amber-600"); if(amberText) { amberText.style.display = "none"; } card.querySelectorAll("button").forEach(b => { if(b.textContent.includes("Activar")) { b.style.display = "none"; } }); const numBadge = card.querySelector(".w-8.h-8, .w-9.h-9"); if(numBadge) { numBadge.className = numBadge.className.replace("bg-gray-100", "bg-emerald-50").replace("border-gray-200", "border-emerald-200").replace("text-gray-500", "text-emerald-600"); numBadge.innerHTML = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check w-4 h-4 text-emerald-600\"><path d=\"M20 6 9 17l-5-5\"></path></svg>"; } } }); }, 250);'''

new_content = re.sub(old_timeout, new_timeout, content)
with open("panel-candidatos/assets/index-BF1UmWzM.js", "w") as f:
    f.write(new_content)
print("Done")
